name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensures all history is fetched so git operations work correctly

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Hugging Face Token for Authentication
      run: echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> $GITHUB_ENV

    - name: Set up Git configuration
      run: |
        git config --global user.email "ze.zohaemaan@gmail.com"
        git config --global user.name "ZohaEmaan01"

    - name: Deploy to Hugging Face Space
      run: |
        pip install huggingface_hub
        huggingface-cli login --token $HF_TOKEN
        git remote add space https://huggingface.co/spaces/z0haEmaan/iris-flower-predictor
        git push --force https://huggingface.co/spaces/z0haEmaan/iris-flower-predictor main
