name: Deploy ML Model to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Hugging Face Token
      run: echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> $GITHUB_ENV

    - name: Deploy to Hugging Face Spaces
      run: |
        pip install huggingface_hub
        huggingface-cli login --token $HF_TOKEN
        huggingface-cli repo create "z0haEmaan/iris-flower-predictor" --type space --yes  # Correct repo name format
        git clone https://huggingface.co/spaces/z0haEmaan/iris-flower-predictor
        cd iris-flower-predictor
        cp -r ../* .
        git add .
        git commit -m "Deploy model"
        git push
